import {loadQuizFromFirebase,saveAttemptToFirebase} from './firebase.js';import {watchUser,isPremium} from './auth.js';import {loadQuizFromSupabase,saveAttemptToSupabase} from './supabase.js';
const $=s=>document.querySelector(s);let quiz,cur=0,ans={},left=0,timer,student={},currentUser=null,currentProfile=null;watchUser((u,p)=>{currentUser=u;currentProfile=p});
$('#startForm').onsubmit=async e=>{e.preventDefault();student={name:$('#studentName').value,id:$('#studentId').value};try{quiz=await load($('#source').value,$('#quizId').value);start()}catch(err){alert(err.message)}};
async function load(src,id){if(src==='firebase')return loadQuizFromFirebase(id);if(src==='supabase')return loadQuizFromSupabase(id);let r=await fetch('data/quizzes.json');let all=await r.json();return all[id]||all['sample-quiz']}
function start(){if(quiz.premium&&!isPremium(currentProfile))throw Error('Premium test. Please login and upgrade to premium.');if(!quiz?.questions?.length)throw Error('Invalid quiz');cur=0;ans={};left=(quiz.durationMinutes||10)*60;$('#setup').classList.add('hidden');$('#test').classList.remove('hidden');$('#title').textContent=quiz.title;$('#desc').textContent=quiz.description;$('#meta').textContent=`${quiz.questions.length} questions • ${quiz.durationMinutes} min`;render();clearInterval(timer);timer=setInterval(tick,1000);tick()}
function tick(){let m=String(Math.floor(left/60)).padStart(2,'0'),s=String(left%60).padStart(2,'0');$('#timer').textContent=`${m}:${s}`;if(left--<=0)finish()}
function render(){let q=quiz.questions[cur];$('#bar').style.width=((cur+1)/quiz.questions.length*100)+'%';$('#box').innerHTML=`<div class="question"><h3>Question ${cur+1}/${quiz.questions.length}</h3><p>${esc(q.question)}</p>${q.options.map((o,i)=>`<label class="option ${ans[cur]===i?'selected':''}"><input type="radio" name="a" value="${i}" ${ans[cur]===i?'checked':''}> ${esc(o)}</label>`).join('')}</div>`;document.querySelectorAll('[name=a]').forEach(x=>x.onchange=()=>{ans[cur]=+x.value;render()});$('#prev').disabled=cur===0;$('#next').disabled=cur===quiz.questions.length-1}
$('#prev').onclick=()=>{if(cur>0){cur--;render()}};$('#next').onclick=()=>{if(cur<quiz.questions.length-1){cur++;render()}};$('#submit').onclick=()=>confirm('Submit test?')&&finish();
async function finish(){clearInterval(timer);let c=0;quiz.questions.forEach((q,i)=>{if(ans[i]===q.correctIndex)c++});let pct=Math.round(c/quiz.questions.length*100);$('#test').classList.add('hidden');$('#result').classList.remove('hidden');$('#score').textContent=`${c}/${quiz.questions.length} correct (${pct}%)`;$('#summary').textContent=pct>=(quiz.passingScore||50)?'Passed. Keep your streak going.':'Review weak areas and reattempt.';$('#review').innerHTML=quiz.questions.map((q,i)=>`<div class="card"><b>Q${i+1}. ${esc(q.question)}</b><p>Your: ${ans[i]!=null?esc(q.options[ans[i]]):'Not answered'}</p><p><b>Correct:</b> ${esc(q.options[q.correctIndex])}</p><p class="sub">${esc(q.explanation||'')}</p></div>`).join('');let attempt={quizId:quiz.id,student,answers:ans,score:pct};try{await saveAttemptToFirebase(attempt)}catch{}try{await saveAttemptToSupabase(attempt)}catch{}}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
